templates_attributes = {}
templates_attributes['IDD594']       ={'type': 'Carboxylic_Acid','modelpka':3.90, 'titratableatoms': ['O1', 'O2','C']}
templates_attributes['CarboxyGroup'] ={'type': 'Carboxylic_Acid','modelpka':4.75, 'titratableatoms': ['O10', 'O20','C3']}
templates_attributes['AceticAcid']   ={'type': 'Carboxylic_Acid','modelpka':4.80, 'titratableatoms': ['O1', 'O2','C']}
templates_attributes['imidazole']    ={'type': 'Base','modelpka':6.30, 'titratableatoms': ['N10','C10','N20','C30','C40']}
templates_attributes['piperidine']   ={'type': 'Base','modelpka':6.33, 'titratableatoms': ['XXX1']}
templates_attributes['PropanoicAcid']={'type': 'Carboxylic_Acid','modelpka':4.20, 'titratableatoms': ['O10', 'O20','C30']}
templates_attributes['acetylsalicylicacid']   ={'type': 'Carboxylic_Acid','modelpka':4.99, 'titratableatoms': ['O1', 'O2','C','C30','C50','C80','C60','C40']}
#templates_attributes['CRAP']         ={'type': 'Acid','modelpka':4.555, 'titratableatoms': ['O10', 'O20','C30']}
